services:
  node:
    container_name: node-container
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - mysql
    networks:
      - foodlink-network

  mysql:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - foodlink-network

  nginx:
    container_name: nginx-container
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/api.surunserver.store/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/api.surunserver.store/privkey.pem:/etc/nginx/certs/privkey.pem
    networks:
      - foodlink-network

networks:
  foodlink-network:
    driver: bridge

volumes:
  mysql-data:
